apiVersion: v1
kind: Namespace
metadata:
  name: hellogo
---
apiVersion: v1
imagePullSecrets:
- name: key-for-docker
kind: ServiceAccount
metadata:
  name: hellogo-auth
  namespace: hellogo
---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImNXbDFaM1Z2WW1sdU9tUmphM0pmY0dGMFgxSkZjMjVpUmkxcmFWcFZNWFJ0VVZkWGVUTlJNV2xNWDBwbk5BPT0iCgkJfQoJfQp9
kind: Secret
metadata:
  name: key-for-docker
  namespace: hellogo
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: hellogo
  namespace: hellogo
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    name: hellogo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo
  namespace: hellogo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hellogo
  template:
    metadata:
      labels:
        name: hellogo
    spec:
      containers:
      - image: qiuguobin/hellogo:69d7e603775155f8310809727bbfddc1e0bec9f1
        imagePullPolicy: Always
        name: hellogo
        ports:
        - containerPort: 8000
      initContainers:
      - command:
        - goose
        - up
        env:
        - name: GOOSE_DRIVER
          value: mysql
        - name: GOOSE_DBSTRING
          value: root:111111@tcp(mysql-service.mysql.svc.cluster.local:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
        - name: GOOSE_MIGRATION_DIR
          value: /app/db/migrations
        image: qiuguobin/hellogo:69d7e603775155f8310809727bbfddc1e0bec9f1
        name: migration
      serviceAccountName: hellogo-auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
  name: nginx-hellogo
  namespace: hellogo
spec:
  ingressClassName: nginx
  rules:
  - host: hellogo.example.com
    http:
      paths:
      - backend:
          service:
            name: hellogo
            port:
              name: http
        path: /
        pathType: Prefix
