apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deploy.yaml
images:
- name: qiuguobin/hellogo
  newName: qiuguobin/hellogo
  newTag: 69d7e603775155f8310809727bbfddc1e0bec9f1
